# Generated by Django 5.0.6 on 2024-06-16 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
